# for now only a test appset for common ns-es

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-common-nsconfig 
  namespace: argocd-admin
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: "new-test"
      values:
        valuesFile: "new-test.yaml"
        targetRevision: "master"
  template:
    metadata:
      name: '{{name}}-helm-common-nsconfig'
    spec:
      project: default
      syncPolicy:
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 5
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      source:
        repoURL: 'https://github.com/aleksander124/argocd.git'
        targetRevision: '{{values.targetRevision}}'
        path: 'namespace-config'
        helm:
          valueFiles:
          - 'cluster-values/{{values.valuesFile}}'
          - 'values.yaml' # seems to be added by default anyway
          version: v3
      destination:
        server: '{{server}}'
        namespace: argocd-admin
