{{- range .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}-{{ .clusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ .name }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .clusterRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}